# Generated by Django 2.1.7 on 2019-05-02 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_and_registraion', models.CharField(max_length=255)),
                ('induction_programme', models.IntegerField()),
                ('welcome_address', models.CharField(max_length=255)),
                ('induction_lectures', models.CharField(max_length=255)),
                ('induction_of_new_members', models.CharField(max_length=255)),
                ('welcome_address_by_president', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=200)),
                ('photograph', models.CharField(max_length=255)),
                ('documentary_on_cpn', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('annual_general_meeting', models.CharField(max_length=255)),
                ('dinner_and_presentation_of_awards_and_certificate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_paper', models.CharField(default='', max_length=100)),
                ('conference_title', models.CharField(default='', max_length=100)),
                ('upload_paper', models.FileField(upload_to='')),
                ('proceeding_paper_title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('speaker', models.CharField(default='', max_length=100)),
                ('other_authors', models.CharField(default='', max_length=100)),
                ('conference_location', models.CharField(default='', max_length=100)),
                ('conference_start_date', models.DateField(default=1994)),
                ('conference_end_date', models.DateField(default=1994)),
                ('place_of_publication', models.CharField(blank=True, max_length=100)),
                ('online_link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('membership_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_title', models.CharField(max_length=50)),
                ('biography', models.TextField(max_length=1000)),
                ('twitter', models.CharField(blank=True, max_length=16)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('conference_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencetitle', to='schedule.Event')),
                ('speaker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakername', to='schedule.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indivual_membership', models.CharField(max_length=150)),
                ('corporate_membership', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='entry_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membersentry', to='schedule.TypeOfMembership'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='schedule.Event'),
        ),
    ]
