# Generated by Django 2.1.7 on 2019-05-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofmembership',
            old_name='corporate_membership',
            new_name='membership_type',
        ),
        migrations.RemoveField(
            model_name='typeofmembership',
            name='indivual_membership',
        ),
    ]
