# Generated by Django 2.1.7 on 2019-05-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190501_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='speakername', to='schedule.Speaker'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speaker_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speaker_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
