# Generated by Django 2.1.7 on 2019-05-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190501_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='conference_paper',
        ),
    ]
