# Generated by Django 2.1.7 on 2019-05-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190501_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='phone_number',
            field=models.CharField(default='', max_length=150),
        ),
    ]
